server:
  port: 80
#eureka 客户端配置
eureka:
  client:
    register-with-eureka: true #将自己注册到 EurekaServer
    fetch-registry: true  #是否从从 EurekaServer 抓取注册信息，默认为 true, 单节点无所谓，
    #集群必须设置为 true 才能配合 ribbon 使用负载均衡
    service-url:   #表示将自己注册到哪个 eurekaServer
#      defaultZone: http://192.168.111.137:9001/eureka
      defaultZone: http://eureka9001.com:9001/eureka, http://eureka9002.com:9002/eureka

spring:
  application:
    name: MEMBER-COMSUMER-80
